#!/usr/bin/env bash

# installing tailwind without npm
curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
chmod +x tailwindcss-linux-x64
mv tailwindcss-macos-arm64 tailwindcss
